### ISSUE TITLE
Cadê a aula 3?

### ISSUE THREAD

**Issue by ap3ufersa** [draggner/ap3_2024.1_daviSamuel#1]
Onde estão os arquivos da aula 3?

**Comment by draggner** [comment]
Um momento, encaminharei as alterações. Esta uma zona programar em Java😀

![TestaAluno java - ap3_2024 1_daviSamuel - Visual Studio Code 28_07_2024 17_18_13](https://github.com/user-attachments/assets/a4c94358-1f2c-4fcb-a8a4-b1ef2e7fa253)
